// Generated by gencpp from file llm_agents/LLMResponse.msg
// DO NOT EDIT!


#ifndef LLM_AGENTS_MESSAGE_LLMRESPONSE_H
#define LLM_AGENTS_MESSAGE_LLMRESPONSE_H

#include <ros/service_traits.h>


#include <llm_agents/LLMResponseRequest.h>
#include <llm_agents/LLMResponseResponse.h>


namespace llm_agents
{

struct LLMResponse
{

typedef LLMResponseRequest Request;
typedef LLMResponseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LLMResponse
} // namespace llm_agents


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::llm_agents::LLMResponse > {
  static const char* value()
  {
    return "59dd40d73b99b23145c3779b008631a3";
  }

  static const char* value(const ::llm_agents::LLMResponse&) { return value(); }
};

template<>
struct DataType< ::llm_agents::LLMResponse > {
  static const char* value()
  {
    return "llm_agents/LLMResponse";
  }

  static const char* value(const ::llm_agents::LLMResponse&) { return value(); }
};


// service_traits::MD5Sum< ::llm_agents::LLMResponseRequest> should match
// service_traits::MD5Sum< ::llm_agents::LLMResponse >
template<>
struct MD5Sum< ::llm_agents::LLMResponseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::llm_agents::LLMResponse >::value();
  }
  static const char* value(const ::llm_agents::LLMResponseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::llm_agents::LLMResponseRequest> should match
// service_traits::DataType< ::llm_agents::LLMResponse >
template<>
struct DataType< ::llm_agents::LLMResponseRequest>
{
  static const char* value()
  {
    return DataType< ::llm_agents::LLMResponse >::value();
  }
  static const char* value(const ::llm_agents::LLMResponseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::llm_agents::LLMResponseResponse> should match
// service_traits::MD5Sum< ::llm_agents::LLMResponse >
template<>
struct MD5Sum< ::llm_agents::LLMResponseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::llm_agents::LLMResponse >::value();
  }
  static const char* value(const ::llm_agents::LLMResponseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::llm_agents::LLMResponseResponse> should match
// service_traits::DataType< ::llm_agents::LLMResponse >
template<>
struct DataType< ::llm_agents::LLMResponseResponse>
{
  static const char* value()
  {
    return DataType< ::llm_agents::LLMResponse >::value();
  }
  static const char* value(const ::llm_agents::LLMResponseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LLM_AGENTS_MESSAGE_LLMRESPONSE_H
