// Generated by gencpp from file llm_agents/LLMResponseResponse.msg
// DO NOT EDIT!


#ifndef LLM_AGENTS_MESSAGE_LLMRESPONSERESPONSE_H
#define LLM_AGENTS_MESSAGE_LLMRESPONSERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace llm_agents
{
template <class ContainerAllocator>
struct LLMResponseResponse_
{
  typedef LLMResponseResponse_<ContainerAllocator> Type;

  LLMResponseResponse_()
    : response()  {
    }
  LLMResponseResponse_(const ContainerAllocator& _alloc)
    : response(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _response_type;
  _response_type response;





  typedef boost::shared_ptr< ::llm_agents::LLMResponseResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::llm_agents::LLMResponseResponse_<ContainerAllocator> const> ConstPtr;

}; // struct LLMResponseResponse_

typedef ::llm_agents::LLMResponseResponse_<std::allocator<void> > LLMResponseResponse;

typedef boost::shared_ptr< ::llm_agents::LLMResponseResponse > LLMResponseResponsePtr;
typedef boost::shared_ptr< ::llm_agents::LLMResponseResponse const> LLMResponseResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::llm_agents::LLMResponseResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::llm_agents::LLMResponseResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::llm_agents::LLMResponseResponse_<ContainerAllocator1> & lhs, const ::llm_agents::LLMResponseResponse_<ContainerAllocator2> & rhs)
{
  return lhs.response == rhs.response;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::llm_agents::LLMResponseResponse_<ContainerAllocator1> & lhs, const ::llm_agents::LLMResponseResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace llm_agents

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::llm_agents::LLMResponseResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::llm_agents::LLMResponseResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::llm_agents::LLMResponseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::llm_agents::LLMResponseResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::llm_agents::LLMResponseResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::llm_agents::LLMResponseResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::llm_agents::LLMResponseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6de314e2dc76fbff2b6244a6ad70b68d";
  }

  static const char* value(const ::llm_agents::LLMResponseResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6de314e2dc76fbffULL;
  static const uint64_t static_value2 = 0x2b6244a6ad70b68dULL;
};

template<class ContainerAllocator>
struct DataType< ::llm_agents::LLMResponseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "llm_agents/LLMResponseResponse";
  }

  static const char* value(const ::llm_agents::LLMResponseResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::llm_agents::LLMResponseResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string response\n"
"\n"
;
  }

  static const char* value(const ::llm_agents::LLMResponseResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::llm_agents::LLMResponseResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.response);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct LLMResponseResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::llm_agents::LLMResponseResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::llm_agents::LLMResponseResponse_<ContainerAllocator>& v)
  {
    s << indent << "response: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.response);
  }
};

} // namespace message_operations
} // namespace ros

#endif // LLM_AGENTS_MESSAGE_LLMRESPONSERESPONSE_H
